### ISSUE TITLE
Component does not update when filters state changes

### ISSUE THREAD

**Issue by bmessinoaviatrix** [tiagofernandez/mui-querybuilder#1]
when a state object is passed in as filters props, then the state object is updated, the querybuilder component does not update to reflect the new filters props.

In dynamic options example, http://tiagofernandez.com/mui-querybuilder/iframe.html?id=muiquerybuilder--supported-types&viewMode=docs#dynamic-options, the Button that updates filters state is 

                   <Button
                        color="primary"
                        disabled={loaded}
                        variant="outlined"
                        onClick={() => {
                            const updatedFilters = [...filters];
                             [
                                { label: "January", value: 1 },
                                { label: "February", value: 2 },
                                { label: "March", value: 3 },
                                { label: "April", value: 4 },
                                { label: "May", value: 5 },
                                { label: "June", value: 6 },
                                { label: "July", value: 7 },
                                { label: "August", value: 8 },
                                { label: "September", value: 9 },
                                { label: "October", value: 10 },
                                { label: "November", value: 11 },
                                { label: "December", value: 12 },
                            ].forEach(month => {
                                updatedFilters[0].options[0].options.push(month);
                            });
                            setFilters(updatedFilters);
                            setLoaded(true);
                        }}
                    >

the problem with this example is the const updatedFilters = [...filters]; is making a shallow clone of the filters state so when the forEach function makes modifications to the inner object it is mutating the state. This is making the changes appear in the filters object. The setFilters(updatedFilters); does not make a difference. 

To test this remove the setFilters(updatedFilters); line and it will still work.

**Comment by tiagofernandez** [comment]
Thanks for reporting!

Indeed you're right, in this example `setFilters(updatedFilters);` is not necessary. I'm seeing the months are populated in different scenarios:
* When the `filters` state is mutated directly, e.g. by pushing the months directly into the options;
* When using `setFilters` to reset all filters at once, meaning the component is still updating the options the filters change.

Is there anything to fix that I could be failing to see, other than this example?
