### ISSUE TITLE
Invalid hook call, wrong react version?

### ISSUE THREAD

**Issue by fedyunin** [tiagofernandez/mui-querybuilder#2]
Hello! I faced with next issue:

```
https://reactjs.org/warnings/invalid-hook-call-warning.html
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

In my project used react 17.0.2
    "react": "^17.0.1",
    "react-dom": "^17.0.1",

Do I need update react version for mui-builder too? Or this is can be other issue?

**Comment by tiagofernandez** [comment]
Just built and analyzed MUI-QueryBuilder's bundle to make sure, and it's not including React. I've tested it locally with React `17.0.2`, and couldn't spot the issue in any of the existing stories. Please refer to [those examples](https://github.com/tiagofernandez/mui-querybuilder/blob/main/stories/QueryBuilder.stories.jsx) for the recommended usage, or post a story demonstrating the issue so I can reproduce it.

**Comment by fedyunin** [comment]
Ok I will try your examples and check maybe it's my error. Thanks for quick answer!

**Comment by fedyunin** [comment]
I review my project config and found issue with dependencies. This issue was on my side.

**Comment by llaver** [comment]
@fedyunin can you give more details as to the issue with your dependencies? I am having this same issue, but only when deploying a build. The issue does not occur when testing locally. 

@tiagofernandez do you have any ideas what could be happening? Need to figure out a solution for this ASAP.

**Comment by llaver** [comment]
Update: So this had to do with `3. You might have more than one copy of React in the same app` .

I'm not sure why this happens in a build and not locally, or what kind of change would be needed in the library to start avoiding the problem, but I suggest the issue be reopened as the problem persists.
More information can be found here:
https://github.com/facebook/react/issues/13991

Note: I tested with react 16.13.1, 17.0.0, 17.0.1, and 17.0.2 so not version specific. 

The workaround is in the comments: add the following alias to your webpack config:
```
      // webpack.config.js
      alias: {
        react: path.resolve('./node_modules/react')
      }
```

If you used create-react-app and have not ejected (and don't want to) then you will need to use [react-app-rewired](https://www.npmjs.com/package/react-app-rewired) or a similar library:
```
const path = require("path");
const { override, addWebpackAlias } = require("customize-cra");

/* config-overrides.js */

module.exports = override(
  addWebpackAlias({
    react: path.resolve("./node_modules/react"),
  })
);
```
